### ISSUE TITLE
[This is not a contribution] Target Weight Set to 100 instead then 0

### ISSUE THREAD

**Issue by osnm91** [Kong/deck#364] opened 2021-05-04 17:40 UTC
Hi,

I am experiencing a problem with deck sync.

I specify weight: 0 on an upstream target but a weight of 100 is instead applied on the same target after running deck sync. 
It seems is taking the default value as for: https://docs.konghq.com/gateway-oss/2.4.x/admin-api/.

Kong Version:  2.4.0
Deck version v1.6.0

**Comment by hbagdi** [comment] 2021-05-05 23:06
This is due to https://github.com/Kong/deck/blob/main/utils/constants.go#L28.
This gives us another reason to get #89 moving forward.

**Comment by nunmelix** [comment] 2021-05-06 12:03
however, I explicitly specified a weight of 0 for the specific target. 
Why Deck ignored it and took 100 as default value ?

**Comment by hbagdi** [comment] 2021-05-06 14:39
>  Why Deck ignored it and took 100 as default value ?

This has to do with how reflections in Go work. 0 is considered same as `nil` and the default of `100` (hardcoded in the code) takes effect.

**Comment by osnm91** [comment] 2021-06-10 18:18
I have been looking at this a little bit.

I recompiled Deck from source and set the default for the upstream target weight to 0. 

It seems that also setting the default value to 0 for the target upstream weight would not solve the problem.

It seems that when the weight is set to 0, Kong remove the all target and deck error.

The error is:

`while processing event: {Create} target XXXX:80 for upstream 5569b34b-084f-4382-b5b6-7c5f306f43c9 failed: HTTP status 404 (message: "could not find the entity with primary key '{id=\"70d72611-2261-4d36-b2e2-48cf849ac60e\"}'")`

**Comment by hbagdi** [comment] 2021-06-10 18:34
> It seems that when the weight is set to 0, Kong remove the all target and deck error.

Kong allows 0 as the weight so this probably is a bug in Kong if Kong actually removes the target with weight 0.
@locao, any insights?

**Comment by locao** [comment] 2021-06-10 20:30
Yes, Kong allows targets with weight 0, but before 2.4.1 there was a bug where the Admin API would not list them, even if they existed. It was fixed by Kong/kong#7094

**Comment by osnm91** [comment] 2021-06-11 08:29
Ok, we are running 2.4.0 in Hybrid Mode.
I will upgrade to 2.4.1 and check if this is fixed.

In the case this is fixed, is there any reason we could not solve this bug removing this line: https://github.com/Kong/deck/blob/main/file/builder.go#L687
? I may miss other implications so let me know if this is feasible.

It seems the problem is the mergo library Deck uses here: https://github.com/Kong/deck/blob/e02003af0b121f3128746221cbadb24e44ea347f/utils/defaulter.go#L114.

As from Mergo README indeed (https://github.com/imdario/mergo/blob/master/README.md): 

> Mergo merges same-type structs and maps by setting default values in zero-value fields. 

Since Kong accept 0 as value, I do not see the reason to set a default value in here.
I think that set a default value in here is a bit risky because if I explicitly set a value in the yaml I do not want another value to be set, I rather prefer my pipeline to fail and give me an error.

In our case we found our canary cluster set accidentally to 100% when we wanted to set it to 0 following a bad deploy.
It is true that there is the diff but I anyway think that deck should not change a value specified in the yaml with something else.

Let me know if this change looks good to you or if I am missing other implication.
I am available to open a MR.

**Comment by hbagdi** [comment] 2021-06-16 21:25
We got #419 merged in and it will be released in future.
Could you insert the following snippet in your state file and verify if it solves your problem?

```yaml
_info:
  defaults:
    target:
      weight: 0
```

**Comment by osnm91** [comment] 2021-09-24 16:01
I tested this.

I am now able to set the weight to 0 and back to 100 using the Kong APIs.
However it seems that when weight is set to 0curl http://127.0.0.1:8001/upstreams/shazam/targets/0

**Comment by hbagdi** [comment] 2021-09-30 19:31
> The only thing to point out is that a GET for http://adminapi:8001/upstreams//targets/<target_id> returns {"message":"Not found"} when weight is set to 0. Not sure if this is expected.

@locao is that expected?

**Comment by locao** [comment] 2021-09-30 19:49
> @locao is that expected?

It wasn't expected, but I was able to reproduce the issue here. I will write a fix for this.

**Comment by hbagdi** [comment] 2021-09-30 20:48
Going to close since this is now fixed. Please re-open if needed.

**Closed by hbagdi** 2021-09-30 20:48 UTC
Labels: bug
