### ISSUE TITLE
'deck diff' show difference for service.name

### ISSUE THREAD

**Issue by dynastini1** [Kong/deck#213] opened 2020-09-21 07:36 UTC
When using such configuration:
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test

routes:
- name: test
  service:
    name: test
  paths:
  - "/test1"
  path_handling: v0
  https_redirect_status_code: 426
```

```deck diff -s test.yaml``` can't handle 'service.name' in 'routes' configuration and showing difference:
```diff
updating route test1  {
-  "created_at": 1.600672019e+09,
   "https_redirect_status_code": 426,
   "id": "d876c109-8ed2-48b5-9cb5-31b7379ab985",
   "name": "test1",
   "path_handling": "v0",
   "paths": [
     "/test1"
   ],
   "preserve_host": false,
   "protocols": [
     "http",
     "https"
   ],
   "regex_priority": 0,
   "service": {
-    "id": "9af11672-7781-4af2-b8e7-383d435a2bf1"
+    "name": "test"
   },
   "strip_path": false,
   "tags": [
     "test"
   ],
-  "updated_at": 1.600672019e+09
 }
```

**Comment by hbagdi** [comment] 2020-09-21 16:18
That is against the spec of kong's declarative configuration.

Please instead use:

```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test

routes:
- name: test
  service: test
  paths:
  - "/test1"
  path_handling: v0
  https_redirect_status_code: 426
```

And please ensure that `test` service is defined as well.

**Comment by dynastini1** [comment] 2020-09-21 16:27
Hello, thx for your response.
Sadly your configuration didn't pass deck validation:
```deck validate -s test.yaml```
```
Error: reading file: validating file content: 1 errors occurred:
        routes.0.service: Invalid type. Expected: object, given: string
```
And I'm run this command before ```diff``` and ```sync``` in my script.

**Comment by hbagdi** [comment] 2020-09-21 16:46
I see.
There are two things that are going wrong here:
- Service inside the route should not be an object but rather a string as per kong's specification of declarative configuration. I do not recall the behavior or decision that we made in deck in the past. This requires more investigation and likely some git spelunking.
- The diff showed because of organizing the output in the way you have mentioned seems wrong and is likely a bug but I can't pinpoint the root cause right now. A user should be able to define a route and then reference a service (this is opposite of the usual case where routes of a service are nested under the service). This requires more investigation as well.


Until we have a path forward here, I recommend you define [routes nested under the associated service](https://github.com/Kong/deck/blob/3d73c13e476442fbca358841fd4e7046ffd6d214/kong.yaml#L5-L14). This works well and you should not encounter any problems.

**Comment by dynastini1** [comment] 2020-09-21 16:56
Thanks for the explanation!

**Comment by hbagdi** [comment] 2021-03-29 10:15
Opened in by mistake in the bulk editing mode. Closing again.

**Closed** 2022-05-05 13:08 UTC
Labels: needs investigation
