### ISSUE TITLE
deck ignores negative for RBAC endpoints

### ISSUE THREAD

**Issue by simon-kuzin-singtel** [Kong/deck#298] opened 2021-03-26 03:09 UTC
deck ignores values of "negative" attribute of RBAC endpoint_permission resources,  specified in state file. All endpoints are created with negative=false. In fact attribute 'negative' missed from requests deck issues to kong admin API.

deck version 1.5.1

**state file:**
```
- name: workspace-super-admin
  comment: Full access to all endpoints in the workspace
  is_default: false
  endpoint_permissions:
  - workspace: auto-created
    endpoint: '*'
    actions:
    - delete
    - create
    - update
    - read
    negative: false
  - workspace: auto-created
    endpoint: /ca_certificates
    actions:
    - delete
    - create
    - update
    negative: true
  - workspace: auto-created
    endpoint: /ca_certificates/*
    actions:
    - delete
    - create
    - update
    negative: true
```

**deck log**
```
...
build	26-Mar-2021 10:45:25	creating rbac-endpointpermission 01e87685-2271-48f1-ac1e-7c56a19991ee-auto-created-*
build	26-Mar-2021 10:45:25	creating rbac-endpointpermission 01e87685-2271-48f1-ac1e-7c56a19991ee-auto-created-/ca_certificates
...
error	26-Mar-2021 10:45:25	POST /auto-created/rbac/roles/01e87685-2271-48f1-ac1e-7c56a19991ee/endpoints HTTP/1.1
error	26-Mar-2021 10:45:25	Host: 10.170.120.132:8001
error	26-Mar-2021 10:45:25	User-Agent: Go-http-client/1.1
error	26-Mar-2021 10:45:25	Content-Length: 91
error	26-Mar-2021 10:45:25	Content-Type: application/json
error	26-Mar-2021 10:45:25	Accept-Encoding: gzip
error	26-Mar-2021 10:45:25	
error	26-Mar-2021 10:45:25	{"workspace":"auto-created","endpoint":"/ca_certificates","actions":"delete,create,update"}
...
error	26-Mar-2021 10:45:25	POST /auto-created/rbac/roles/01e87685-2271-48f1-ac1e-7c56a19991ee/endpoints HTTP/1.1
error	26-Mar-2021 10:45:25	Host: 10.170.120.132:8001
error	26-Mar-2021 10:45:25	User-Agent: Go-http-client/1.1
error	26-Mar-2021 10:45:25	Content-Length: 93
error	26-Mar-2021 10:45:25	Content-Type: application/json
error	26-Mar-2021 10:45:25	Accept-Encoding: gzip
error	26-Mar-2021 10:45:25	
error	26-Mar-2021 10:45:25	{"workspace":"auto-created","endpoint":"/ca_certificates/*","actions":"delete,create,update"}
...

```

**commandline:**
`$deck --verbose 2 --config deck-conf.yml sync --db-update-propagation-delay 1 --rbac-resources-only --state rbac.yml
`

[rbac.yml.txt](https://github.com/Kong/deck/files/6209133/rbac.yml.txt)
[plan-48205515-JOB1-21.log](https://github.com/Kong/deck/files/6209138/plan-48205515-JOB1-21.log)

**Comment by rainest** [comment] 2021-03-31 22:10
The go-kong issue fixed by https://github.com/Kong/go-kong/pull/32 is the cause of this. It's still present in deck as of now because we haven't yet cut a new go-kong release.

**Closed** 2021-04-06 13:52 UTC
