### ISSUE TITLE
configFilesInDir(): extension match not anchored at end of filename

### ISSUE THREAD

**Issue by mflendrich** [Kong/deck#255] opened 2021-01-07 15:50 UTC
Summary: `configFilesInDir(dir)`, when it traverses the directory tree for yaml/json files, does not reliably identify json|yaml files.

Current behavior: `aaa.yaml.old` and `this-is-not-yaml.pdf` match. It might be the case that `/some/path/yaml/aaa.pdf` matches too, but I haven't checked.
Desired behavior: `aaa.yaml.old`and `this-is-not-yaml.pdf` don't match

The culprit is this regexp https://github.com/Kong/deck/blob/8e68931d7c3c050437d3f30dcd685b6e01246e9d/file/readfile.go#L114

**Comment by hbagdi** [comment] 2021-01-07 16:06
Duplicate of https://github.com/Kong/deck/issues/247

**Comment by waciii-ra** [comment] 2021-01-07 16:39
The File Extension dot is not mentioned.  Address that edge case as well, if and as appropriate, in additional to the End of String Anchor (as represented in the proposed update below):

`exts := regexp.MustCompile("\.[Yy]([Aa])?[Mm][Ll]|[Jj][Ss][Oo][Nn]$")`

Current behavior: `aaayaml` matches
Desired behavior: `aaa.yaml` doesn't match

**Comment by hbagdi** [comment] 2021-01-08 17:20
@waciii-ra That seems correct. A PR would be very welcome if you would like to contribute to the project. Thank you.

**Closed** 2021-01-18 12:15 UTC
Labels: bug, good first issue, help wanted
