### ISSUE TITLE
Handling multiple disjoint tags on a single sync via CI

### ISSUE THREAD

**Issue by dlouzan** [Kong/deck#189] opened 2020-07-14 20:18 UTC
I'd like to ask about the proper, sanctioned way of handling multiple disjoint configurations, probably belonging to different service owners, for which tags and select tags seem to be appropriate.

Our scenario is:

- We'd like to break the configuration file into multiple services, each with their own tag `select_tags`, e.g. `service1` and `service2`, and multiple files for each service, probably one for the services/routes and another for the consumers e.g. `service1/services.yaml` and `service1/consumers.yaml`
- Whenever full CI passes and something is merged to master, deploy to the running kong
- Do this via sync of the whole directory of configuration files, making sure that what is deployed is exactly what is in the code
- Have the ability to either deploy everything or just a subset of the config, such as only the files / directory relevant to a service

Since deck's strategy is to merge all the tags of the different files in the configuration directory and apply them to all involved entities, this does not work. It requires writing some script that goes through the different directories and apply them in chunks based on the service name (e.g. `deck sync -s kong-conf/service1/` and `deck sync -s kong-conf/service2/`).

Encountering this behaviour of the tags was highly unintuitive for me. If the behaviour is intended (as https://github.com/hbagdi/deck/issues/116 suggests), it should probably be more clearly documented, otherwise reconsider this behaviour. In the lattter case, some rationale would be really welcome 👍 

Thanks!

**Comment by hbagdi** [comment] 2020-07-14 20:43
> Whenever full CI passes and something is merged to master, deploy to the running kong

> Have the ability to either deploy everything or just a subset of the config, such as only the files / directory relevant to a service

The reason you are running into this problem is because the way decK is designed, these two are at odds with each other.
The reason select-tags feature exists is to allow for [distributed configuration](https://deck.yolo42.com/guides/distributed-configuration.html). Now, in your case, you want to do both, incremental updates for specific services and sync the whole thing as well.

Although this is technically possible, my position so far has been that you should script this as you would like because that allows for maximum flexibility and low maintenance.

I'm seeing increasing reports of users wanting to do this but I've not yet figured out a way to add this feature and keep  most users happy.

> probably be more clearly documented

We sure can do this part. Any suggestions?

To implement this feature, we will have to figure out if tags should only be merged on a per-file or per-directory basis and see how it also interacts with the workspaces feature in Kong Enterprise.

**Comment by dlouzan** [comment] 2020-07-14 21:34
@hbagdi Thanks for the really quick answer and explanation.

This is not a blocker for us, since as you mention one can always script over this. It's just cumbersome and a bit weird, at least for me 😅

I'll create a PR later this week with some extra docs about the current behaviour. It's the least we can do, this is an awesome project and I'm hoping we can use it in production 👍 

/cc @bufferoverflow

**Comment by dlouzan** [comment] 2020-07-14 21:40
I forgot, I can't really comment on the Kong Enterprise implications since I haven't got a license and haven't tested it.

**Comment by kcentralsquare** [comment] 2020-08-20 18:43
@hbagdi Would it be possible to add an option to render files with select-tags similar to how the `docker-compose config` command works? Our configuration is split into 2 parts; one file managed by operations and another used to synchronize configurations managed from a self-service UI for customers to manage a subset of consumers.

**Comment by hbagdi** [comment] 2020-08-20 21:11
> @hbagdi Would it be possible to add an option to render files with select-tags similar to how the docker-compose config command works?

Interesting. Can you please elaborate a little more? Bonus points for a small example to demonstrate the inputs and outputs.

I've been thinking a little bit around this but I want to know more about your use case before I start rambling on.

**Comment by kcentralsquare** [comment] 2021-03-22 13:08
@hbagdi Any progress on this issue? Thoughts or feedback on the `docker-compose` solution?

**Comment by hbagdi** [comment] 2021-03-29 14:45
@kcentralsquare For your use-case, distributed configuration is not a workaround, it is the actual solution and the feature was designed with your use-case in mind.
In your example, you start with the assumption that some resources, tagged as `external` will not be managed by decK. Later in your example, you switch to using decK to manage those resources. You either want to manage a resource using decK or not using a decK. There is no middle ground here.
Hope that helps!

**Comment by kcentralsquare** [comment] 2021-03-30 21:42
@hbagdi My use case was a bad example, I'll admit. I still think the ability to pre-render the YAML before applying would give developers more insight into the resulting configuration applied by decK.

In the absence of that functionality, documentation should mention the way decK applies all `select_tags` to all resources when multiple `--state` arguments are supplied and an error/warning when attempting to do so via the CLI:

> Tags in the `select_tags` directive will be combined and applied to ALL resources

**Comment by hbagdi** [comment] 2021-03-31 09:33
> @hbagdi My use case was a bad example, I'll admit. I still think the ability to pre-render the YAML before applying would give developers more insight into the resulting configuration applied by decK.

decK merges the YAML files you give it. Use any YAML tooling to generate it. I think pre-rendering makes sense but there are not enough use-cases to support it (yet). Another place where it could be useful is #191.


> In the absence of that functionality, documentation should mention the way decK applies all select_tags to all resources when multiple --state arguments are supplied and an error/warning when attempting to do so via the CLI:

Do you mind sending us a PR for it on the https://github.com/kong/docs.konghq.com site?

**Comment by hbagdi** [comment] 2021-05-25 17:26
Closing this due to lack of activity. Please re-open if needed.

**Closed by hbagdi** 2021-05-25 17:26 UTC
Labels: question
