### ISSUE TITLE
Error dumping file from kong docker container

### ISSUE THREAD

**Issue by ggcaponetto** [Kong/deck#371] opened 2021-05-06 21:26 UTC
Hello

I have set up Kong, Konga and Postgres in a docker compose file. Everything is up and running.

If I ping the Kong admin API everything is ok.

``docker run --network=gateway_default -e DECK_KONG_ADDR=http://kong:8001 kong/deck ping`` --> ``Successfully connected to Kong! Kong version:  2.4.0``

But if I try to dump the kong.yaml with the command

``docker run --network=gateway_default -e DECK_KONG_ADDR=http://kong:8001 kong/deck dump``

i get the error

 ``
Error: writing file: open kong.yaml: permission denied
writing file: open kong.yaml: permission denied
``

The ``deck dump`` and ``deck sync`` are working if installed on the host (no docker).

My compose file is:

```
version: "3.9"
services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5433:5433
    restart: unless-stopped
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    links:
      - kong-database
    depends_on:
      - kong-database
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    volumes:
      - ./config:/config
    restart: unless-stopped
    depends_on:
      - kong-migration
  konga:
    image: pantsel/konga
    container_name: konga
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    restart: unless-stopped
    depends_on:
      - kong-database
```

**Comment by paulgreg** [comment] 2021-05-11 13:26
I think the problem is that deck, running in docker, tries to write a file inside the docker container, which has not right to do.

I think the solution is to mount a volume on your computer to permit docker to write the file.

You can try something like `docker run --network=gateway_default -e DECK_KONG_ADDR=http://kong:8001 -v ${PWD}/:/mnt/deck kong/deck dump -o /mnt/deck/dump.yaml`

**Comment by GGabriele** [comment] 2022-01-06 14:21
Hi @ggcaponetto,
@paulgreg is right here (thanks for commenting!), mounting a volume and use it as the output folder for `deck` will fix the problem, and it's probably what you **want** to do even if this problem didn't materialize in the first place, as that's what will allow you to persist the dumped file.

Closing this now, but feel free to open a new issue or comment back if you have additional questions!

**Closed by GGabriele** 2022-01-06 14:21 UTC
