### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by bks71** [Kong/deck#206] opened 2020-08-26 18:02 UTC
deck seems to be running fine, but I see this error each time it runs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1527176]

goroutine 6 [running]:
github.com/kong/deck/cmd.sendAnalytics()
        /home/hbagdi/deck/cmd/analytics.go:41 +0x296
github.com/kong/deck/cmd.Execute.func1(0xc000024090)
        /home/hbagdi/deck/cmd/root.go:55 +0x22
created by github.com/kong/deck/cmd.Execute
        /home/hbagdi/deck/cmd/root.go:54 +0x8e
```

Version is 1.2.1

**Comment by hbagdi** [comment] 2020-08-26 18:04
This is a duplicate of #205. The fix is merged and will be released in the next patch release.
No schedule for it yet but a rough guesstimate will be some time in September.

**Closed by hbagdi** 2020-08-26 18:04 UTC
