### ISSUE TITLE
[Deck 1.2.1] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jacky96623** [Kong/deck#205] opened 2020-08-21 03:59 UTC
Hi, I was trying to update my Kong instance with deck, but faced an unexpected error. Please find details below:

Kong Version: 1.5.1 (docker image)
Deck Version: v1.2.1 (install from brew)

Command:
```bash
> deck diff
...
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1527176]

goroutine 6 [running]:
github.com/kong/deck/cmd.sendAnalytics()
        /home/hbagdi/deck/cmd/analytics.go:41 +0x296
github.com/kong/deck/cmd.Execute.func1(0xc000026090)
        /home/hbagdi/deck/cmd/root.go:55 +0x22
created by github.com/kong/deck/cmd.Execute
        /home/hbagdi/deck/cmd/root.go:54 +0x8e
```

Not sure if it is related to recent renaming of repo. Any help would be appreciated.

**Comment by hbagdi** [comment] 2020-08-21 05:26
This is a duplicate of #203

**Closed by hbagdi** 2020-08-21 05:26 UTC
